/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mklinkj.taojwp.ex01;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {
    Calculator calculator = new Calculator();
    assertThat(calculator).isNotNull();
  }
}
