/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mklinkj.taojwp.ex02.client;

import static org.assertj.core.api.Assertions.assertThat;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

@Slf4j
class RateClientTest {
  @Test
  void test() {
    LOGGER.info("### 로거 확인 ... ###: {}", getClass().getCanonicalName());
    RateClient rateClient = new RateClient();
    assertThat(rateClient).isNotNull();
  }
}
