/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mklinkj.taojwp.ex02.server;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

@Slf4j
class RateServerTest {
  @Test
  void test() {
    // 서버 중단 코드를 추가하게 되면 테스트를 추가하자.
    LOGGER.info("### 로거 확인 ... ###: {}", getClass().getCanonicalName());
  }
}
